# Generated by Django 6.0.5 on 2026-05-25 16:36

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('books', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Rental',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('status', models.CharField(choices=[('pending', 'Kutilmoqda'), ('active', 'Faol'), ('overdue', 'Muddati o‘tgan'), ('returned', 'Qaytarilgan'), ('cancelled', 'Bekor qilingan')], default='pending', max_length=20, verbose_name='Status')),
                ('rented_at', models.DateTimeField(blank=True, null=True, verbose_name='Ijaraga olingan sana')),
                ('due_date', models.DateField(verbose_name='Qaytarish muddati')),
                ('returned_at', models.DateTimeField(blank=True, null=True, verbose_name='Qaytarilgan sana')),
                ('rental_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Ijara narxi')),
                ('deposit_amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Garov summasi')),
                ('deposit_returned', models.BooleanField(default=False, verbose_name='Garov qaytarildi')),
                ('deposit_returned_at', models.DateTimeField(blank=True, null=True, verbose_name='Garov qaytarilgan sana')),
                ('extended_days', models.PositiveIntegerField(default=0, verbose_name='Uzaytirilgan kunlar')),
                ('notes', models.TextField(blank=True, verbose_name="Qo'shimcha eslatmalar")),
                ('book_copy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rentals', to='books.bookcopy', verbose_name='Kitob nusxasi')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rentals', to=settings.AUTH_USER_MODEL, verbose_name='Foydalanuvchi')),
            ],
            options={
                'verbose_name': 'Ijara',
                'verbose_name_plural': 'Ijaralar',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RentalExtension',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('extended_by_days', models.PositiveIntegerField(verbose_name='Uzaytirilgan kunlar')),
                ('new_due_date', models.DateField(verbose_name='Yangi muddat')),
                ('reason', models.TextField(blank=True, verbose_name='Sabab')),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_extensions', to=settings.AUTH_USER_MODEL, verbose_name='Tasdiqlagan admin')),
                ('rental', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='extensions', to='rentals.rental', verbose_name='Ijara')),
            ],
            options={
                'verbose_name': 'Ijara uzaytirish',
                'verbose_name_plural': 'Ijara uzaytirishlar',
                'ordering': ['-created_at'],
            },
        ),
    ]
