# Generated by Django 6.0.5 on 2026-05-25 16:36

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SubscriptionPlan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('name', models.CharField(max_length=100, verbose_name='Tarif nomi')),
                ('slug', models.SlugField(unique=True)),
                ('price_monthly', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Oylik narx')),
                ('max_books_per_month', models.PositiveIntegerField(default=2, verbose_name='Oylik kitob limiti')),
                ('max_simultaneous_books', models.PositiveIntegerField(default=1, verbose_name='Bir vaqtda nechta kitob')),
                ('is_unlimited', models.BooleanField(default=False, verbose_name='Cheksiz')),
                ('description', models.TextField(blank=True, verbose_name='Tavsif')),
                ('is_active', models.BooleanField(default=True, verbose_name='Faol')),
            ],
            options={
                'verbose_name': 'Obuna tarifi',
                'verbose_name_plural': 'Obuna tariflari',
                'ordering': ['price_monthly'],
            },
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('status', models.CharField(choices=[('active', 'Faol'), ('expired', 'Muddati tugagan'), ('cancelled', 'Bekor qilingan'), ('pending', 'Kutilmoqda')], default='pending', max_length=20, verbose_name='Status')),
                ('start_date', models.DateField(verbose_name='Boshlanish sanasi')),
                ('end_date', models.DateField(verbose_name='Tugash sanasi')),
                ('cancelled_at', models.DateTimeField(blank=True, null=True, verbose_name='Bekor qilingan sana')),
                ('auto_renew', models.BooleanField(default=True, verbose_name='Avto yangilanish')),
                ('notes', models.TextField(blank=True, verbose_name='Eslatmalar')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to=settings.AUTH_USER_MODEL, verbose_name='Foydalanuvchi')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subscriptions', to='subscriptions.subscriptionplan', verbose_name='Tarif')),
            ],
            options={
                'verbose_name': 'Obuna',
                'verbose_name_plural': 'Obunalar',
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('status', 'active')), fields=('user',), name='unique_active_subscription_per_user')],
            },
        ),
    ]
