# Generated by Django 6.0.5 on 2026-05-31 16:34

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_profile_created_at_alter_profile_updated_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OTPCode',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('code', models.CharField(max_length=6, verbose_name='Kod')),
                ('purpose', models.CharField(choices=[('register', "Ro'yxatdan o'tish"), ('login', 'Kirish'), ('reset_password', 'Parol tiklash')], max_length=20, verbose_name='Maqsad')),
                ('is_used', models.BooleanField(default=False, verbose_name='Ishlatilgan')),
                ('expires_at', models.DateTimeField(verbose_name='Amal qilish muddati')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='otp_codes', to=settings.AUTH_USER_MODEL, verbose_name='Foydalanuvchi')),
            ],
            options={
                'verbose_name': 'OTP kod',
                'verbose_name_plural': 'OTP kodlar',
                'ordering': ['-created_at'],
            },
        ),
    ]
