# Generated by Django 6.0.5 on 2026-06-03 08:51

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('rentals', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Courier',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('phone', models.CharField(max_length=15, verbose_name='Telefon')),
                ('vehicle_type', models.CharField(blank=True, max_length=50, verbose_name='Transport turi')),
                ('vehicle_number', models.CharField(blank=True, max_length=20, verbose_name='Transport raqami')),
                ('is_active', models.BooleanField(default=True, verbose_name='Faol')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='courier_profile', to=settings.AUTH_USER_MODEL, verbose_name='Foydalanuvchi')),
            ],
            options={
                'verbose_name': 'Kuryer',
                'verbose_name_plural': 'Kuryerlar',
            },
        ),
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('delivery_type', models.CharField(choices=[('pickup', 'Olib borish'), ('return', 'Olib kelish')], max_length=20, verbose_name='Turi')),
                ('status', models.CharField(choices=[('pending', 'Kutilmoqda'), ('assigned', 'Tayinlangan'), ('in_transit', "Yo'lda"), ('delivered', 'Yetkazildi'), ('cancelled', 'Bekor qilingan')], default='pending', max_length=20, verbose_name='Status')),
                ('address', models.TextField(verbose_name='Manzil')),
                ('scheduled_date', models.DateField(verbose_name='Rejalashtirilgan sana')),
                ('scheduled_time', models.TimeField(blank=True, null=True, verbose_name='Rejalashtirilgan vaqt')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Bajarilgan vaqt')),
                ('notes', models.TextField(blank=True, verbose_name='Izohlar')),
                ('signature', models.ImageField(blank=True, null=True, upload_to='signatures/', verbose_name='Mijoz imzosi')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='delivery_photos/', verbose_name='Kitob holati rasmi')),
                ('courier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deliveries', to='couriers.courier', verbose_name='Kuryer')),
                ('rental', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deliveries', to='rentals.rental', verbose_name='Ijara')),
            ],
            options={
                'verbose_name': 'Yetkazib berish',
                'verbose_name_plural': 'Yetkazib berishlar',
                'ordering': ['-created_at'],
            },
        ),
    ]
