# Generated by Django 6.0.5 on 2026-05-25 16:36

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('name', models.CharField(max_length=200, verbose_name='Muallif')),
                ('bio', models.TextField(blank=True, verbose_name='Biografiya')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='Tug‘ilgan sana')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='authors/', verbose_name='Rasm')),
            ],
            options={
                'verbose_name': 'Muallif',
                'verbose_name_plural': 'Mualliflar',
            },
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Janr')),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField(blank=True, verbose_name='Tavsif')),
            ],
            options={
                'verbose_name': 'Janr',
                'verbose_name_plural': 'Janrlar',
            },
        ),
        migrations.CreateModel(
            name='Publisher',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('name', models.CharField(max_length=200, verbose_name='Nashriyot')),
                ('country', models.CharField(blank=True, max_length=100, verbose_name='Mamlakat')),
                ('website', models.URLField(blank=True, verbose_name='Veb-sayt')),
            ],
            options={
                'verbose_name': 'Nashriyot',
                'verbose_name_plural': 'Nashriyotlar',
            },
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('title', models.CharField(max_length=255, verbose_name='Kitob nomi')),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField(blank=True, verbose_name='Tavsif')),
                ('isbn', models.CharField(max_length=20, unique=True, verbose_name='ISBN')),
                ('published_date', models.DateField(blank=True, null=True, verbose_name='Nashr etilgan sana')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Narxi')),
                ('stock_quantity', models.PositiveIntegerField(default=0, verbose_name='Zaxiradagi soni')),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='books/', verbose_name='Muqova')),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='books.author')),
                ('genre', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='books.genre')),
                ('publisher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='books.publisher')),
            ],
            options={
                'verbose_name': 'Kitob',
                'verbose_name_plural': 'Kitoblar',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BookCopy',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('copy_code', models.CharField(max_length=50, unique=True, verbose_name='Nusxa kodi')),
                ('status', models.CharField(choices=[('new', 'Yangi'), ('good', 'Yaxshi'), ('fair', "O'rtacha"), ('poor', 'Eskirgan'), ('lost', "Yo'qolgan")], db_index=True, default='good', max_length=20, verbose_name='Holati')),
                ('location', models.CharField(blank=True, max_length=100, verbose_name='Joylashuvi')),
                ('notes', models.TextField(blank=True, verbose_name='Izoh')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='copies', to='books.book', verbose_name='Kitob')),
            ],
            options={
                'verbose_name': 'Kitob nusxasi',
                'verbose_name_plural': 'Kitob nusxalari',
                'ordering': ['copy_code'],
            },
        ),
    ]
