# Generated by Django 6.0.5 on 2026-06-03 08:51

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BookReview',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('rating', models.PositiveSmallIntegerField(help_text='1-5', verbose_name='Reyting')),
                ('review_text', models.TextField(blank=True, verbose_name='Sharh')),
                ('is_approved', models.BooleanField(default=False, verbose_name='Tasdiqlangan')),
            ],
            options={
                'verbose_name': 'Kitob sharhi',
                'verbose_name_plural': 'Kitob sharhlari',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SimilarBook',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('similarity_score', models.DecimalField(decimal_places=2, default=0.0, max_digits=3, verbose_name="O'xshashlik darajasi")),
            ],
            options={
                'verbose_name': "O'xshash kitob",
                'verbose_name_plural': "O'xshash kitoblar",
            },
        ),
        migrations.AddField(
            model_name='book',
            name='image_2',
            field=models.ImageField(blank=True, null=True, upload_to='books/', verbose_name='Rasm 2'),
        ),
        migrations.AddField(
            model_name='book',
            name='image_3',
            field=models.ImageField(blank=True, null=True, upload_to='books/', verbose_name='Rasm 3'),
        ),
        migrations.AddField(
            model_name='book',
            name='image_4',
            field=models.ImageField(blank=True, null=True, upload_to='books/', verbose_name='Rasm 4'),
        ),
        migrations.AddField(
            model_name='book',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Faol'),
        ),
        migrations.AddField(
            model_name='book',
            name='language',
            field=models.CharField(default='uz', max_length=50, verbose_name='Til'),
        ),
        migrations.AddField(
            model_name='book',
            name='max_rental_days',
            field=models.PositiveIntegerField(default=60, verbose_name='Maksimal ijara muddati (kun)'),
        ),
        migrations.AddField(
            model_name='book',
            name='page_count',
            field=models.PositiveIntegerField(default=0, verbose_name='Sahifalar soni'),
        ),
        migrations.AddField(
            model_name='book',
            name='preview_pages',
            field=models.TextField(blank=True, help_text='Bir necha sahifa matni', verbose_name='Preview sahifalar'),
        ),
        migrations.AddField(
            model_name='book',
            name='rating',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=3, verbose_name='Reyting'),
        ),
        migrations.AddField(
            model_name='book',
            name='reviews_count',
            field=models.PositiveIntegerField(default=0, verbose_name='Sharhlar soni'),
        ),
        migrations.AddField(
            model_name='bookcopy',
            name='barcode',
            field=models.CharField(blank=True, max_length=100, unique=True, verbose_name='Barcode/QR kod'),
        ),
        migrations.AddField(
            model_name='bookcopy',
            name='rental_count',
            field=models.PositiveIntegerField(default=0, verbose_name='Necha marta ijaraga berilgan'),
        ),
        migrations.AlterField(
            model_name='book',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='books', to='books.author'),
        ),
        migrations.AlterField(
            model_name='book',
            name='genre',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='books', to='books.genre'),
        ),
        migrations.AlterField(
            model_name='book',
            name='publisher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='books', to='books.publisher'),
        ),
        migrations.AddIndex(
            model_name='book',
            index=models.Index(fields=['slug'], name='books_book_slug_ca552e_idx'),
        ),
        migrations.AddIndex(
            model_name='book',
            index=models.Index(fields=['isbn'], name='books_book_isbn_54becd_idx'),
        ),
        migrations.AddIndex(
            model_name='book',
            index=models.Index(fields=['is_active', 'rating'], name='books_book_is_acti_227b8e_idx'),
        ),
        migrations.AddField(
            model_name='bookreview',
            name='book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='books.book', verbose_name='Kitob'),
        ),
        migrations.AddField(
            model_name='bookreview',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='book_reviews', to=settings.AUTH_USER_MODEL, verbose_name='Foydalanuvchi'),
        ),
        migrations.AddField(
            model_name='similarbook',
            name='book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='similar_books', to='books.book', verbose_name='Kitob'),
        ),
        migrations.AddField(
            model_name='similarbook',
            name='similar_to',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='similar_from', to='books.book', verbose_name="O'xshash kitob"),
        ),
        migrations.AlterUniqueTogether(
            name='bookreview',
            unique_together={('book', 'user')},
        ),
        migrations.AlterUniqueTogether(
            name='similarbook',
            unique_together={('book', 'similar_to')},
        ),
    ]
