# Generated by Django 6.0.5 on 2026-06-03 08:51

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('books', '0002_bookreview_similarbook_book_image_2_book_image_3_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BookNotification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('is_notified', models.BooleanField(default=False, verbose_name='Xabar berildi')),
                ('notified_at', models.DateTimeField(blank=True, null=True, verbose_name='Xabar berilgan vaqt')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification_requests', to='books.book', verbose_name='Kitob')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='book_notifications', to=settings.AUTH_USER_MODEL, verbose_name='Foydalanuvchi')),
            ],
            options={
                'verbose_name': 'Kitob xabarnomasi',
                'verbose_name_plural': 'Kitob xabarnomalar',
                'ordering': ['created_at'],
                'unique_together': {('user', 'book')},
            },
        ),
        migrations.CreateModel(
            name='BookQueue',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('status', models.CharField(choices=[('waiting', 'Kutilmoqda'), ('notified', 'Xabar berildi'), ('fulfilled', 'Bajarildi'), ('cancelled', 'Bekor qilingan'), ('expired', "Muddati o'tgan")], default='waiting', max_length=20, verbose_name='Status')),
                ('position', models.PositiveIntegerField(default=0, verbose_name="Navbatdagi o'rni")),
                ('notified_at', models.DateTimeField(blank=True, null=True, verbose_name='Xabar berilgan vaqt')),
                ('expires_at', models.DateTimeField(blank=True, null=True, verbose_name='Amal qilish muddati')),
                ('notes', models.TextField(blank=True, verbose_name='Izoh')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='queues', to='books.book', verbose_name='Kitob')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='book_queues', to=settings.AUTH_USER_MODEL, verbose_name='Foydalanuvchi')),
            ],
            options={
                'verbose_name': 'Kitob navbati',
                'verbose_name_plural': 'Kitob navbatlari',
                'ordering': ['created_at'],
                'unique_together': {('user', 'book', 'status')},
            },
        ),
    ]
