# Generated by Django 6.0.5 on 2026-06-03 08:51

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('question', models.CharField(max_length=500, verbose_name='Savol')),
                ('answer', models.TextField(verbose_name='Javob')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Tartib')),
                ('is_active', models.BooleanField(default=True, verbose_name='Faol')),
            ],
            options={
                'verbose_name': 'FAQ',
                'verbose_name_plural': 'FAQlar',
                'ordering': ['order', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StaffRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Rol nomi')),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField(blank=True, verbose_name='Tavsif')),
                ('can_manage_books', models.BooleanField(default=False, verbose_name='Kitoblarni boshqarish')),
                ('can_manage_rentals', models.BooleanField(default=False, verbose_name='Ijaralarni boshqarish')),
                ('can_manage_users', models.BooleanField(default=False, verbose_name='Foydalanuvchilarni boshqarish')),
                ('can_manage_subscriptions', models.BooleanField(default=False, verbose_name='Obunalarni boshqarish')),
                ('can_view_reports', models.BooleanField(default=False, verbose_name="Hisobotlarni ko'rish")),
                ('can_manage_settings', models.BooleanField(default=False, verbose_name='Sozlamalarni boshqarish')),
                ('can_manage_couriers', models.BooleanField(default=False, verbose_name='Kuryerlarni boshqarish')),
            ],
            options={
                'verbose_name': 'Xodim roli',
                'verbose_name_plural': 'Xodim rollari',
            },
        ),
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('title', models.CharField(max_length=255, verbose_name='Sarlavha')),
                ('slug', models.SlugField(unique=True)),
                ('content', models.TextField(verbose_name='Matn')),
                ('excerpt', models.TextField(blank=True, verbose_name='Qisqacha')),
                ('status', models.CharField(choices=[('draft', 'Qoralama'), ('published', 'Nashr qilingan'), ('archived', 'Arxivlangan')], default='draft', max_length=20, verbose_name='Status')),
                ('featured_image', models.ImageField(blank=True, null=True, upload_to='blog/', verbose_name='Asosiy rasm')),
                ('published_at', models.DateTimeField(blank=True, null=True, verbose_name='Nashr sanasi')),
                ('views_count', models.PositiveIntegerField(default=0, verbose_name="Ko'rishlar soni")),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='blog_posts', to=settings.AUTH_USER_MODEL, verbose_name='Muallif')),
            ],
            options={
                'verbose_name': 'Blog posti',
                'verbose_name_plural': 'Blog postlari',
                'ordering': ['-published_at'],
            },
        ),
        migrations.CreateModel(
            name='StaffMember',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('employee_id', models.CharField(max_length=50, unique=True, verbose_name='Xodim ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='Faol')),
                ('notes', models.TextField(blank=True, verbose_name='Izohlar')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='staff_profile', to=settings.AUTH_USER_MODEL, verbose_name='Foydalanuvchi')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='staff_members', to='admin_panel.staffrole', verbose_name='Rol')),
            ],
            options={
                'verbose_name': 'Xodim',
                'verbose_name_plural': 'Xodimlar',
            },
        ),
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('action', models.CharField(choices=[('create', 'Yaratildi'), ('update', 'Yangilandi'), ('delete', "O'chirildi"), ('login', 'Kirdi'), ('logout', 'Chiqdi'), ('approve', 'Tasdiqlandi'), ('reject', 'Rad etildi')], max_length=20, verbose_name='Harakat')),
                ('model_name', models.CharField(max_length=100, verbose_name='Model nomi')),
                ('object_id', models.CharField(blank=True, max_length=100, verbose_name='Obyekt ID')),
                ('description', models.TextField(verbose_name='Tavsif')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP manzil')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activity_logs', to=settings.AUTH_USER_MODEL, verbose_name='Foydalanuvchi')),
            ],
            options={
                'verbose_name': 'Faoliyat logi',
                'verbose_name_plural': 'Faoliyat loglari',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'created_at'], name='admin_panel_user_id_a4e85b_idx'), models.Index(fields=['model_name', 'object_id'], name='admin_panel_model_n_a710a1_idx')],
            },
        ),
    ]
