# Generated by Django 6.0.5 on 2026-05-25 16:36

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('books', '0001_initial'),
        ('rentals', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('notification_type', models.CharField(choices=[('rental_reminder', 'Ijara eslatmasi'), ('overdue', "Muddati o'tgan"), ('return_success', 'Kitob qaytarildi'), ('new_book', 'Yangi kitob'), ('queue_available', "Navbatdagi kitob bo'shadi"), ('subscription_expiry', 'Obuna tugayapti')], max_length=30, verbose_name='Turi')),
                ('title', models.CharField(max_length=200, verbose_name='Sarlavha')),
                ('message', models.TextField(verbose_name='Matn')),
                ('is_read', models.BooleanField(default=False, verbose_name="O'qilgan")),
                ('read_at', models.DateTimeField(blank=True, null=True, verbose_name="O'qilgan vaqt")),
                ('related_book', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications', to='books.book', verbose_name="Bog'liq kitob")),
                ('related_rental', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications', to='rentals.rental', verbose_name="Bog'liq ijara")),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL, verbose_name='Foydalanuvchi')),
            ],
            options={
                'verbose_name': 'Bildirishnoma',
                'verbose_name_plural': 'Bildirishnomalar',
                'ordering': ['-created_at'],
            },
        ),
    ]
