# Generated by Django 6.0.5 on 2026-06-03 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('rental_reminder', 'Ijara eslatmasi'), ('rental_due_soon', 'Qaytarish muddati yaqin'), ('overdue', "Muddati o'tgan"), ('return_success', 'Kitob qaytarildi'), ('deposit_returned', 'Garov qaytarildi'), ('new_book', 'Yangi kitob'), ('book_available', "Kitob bo'shadi"), ('queue_available', "Navbatdagi kitob bo'shadi"), ('subscription_expiry', 'Obuna tugayapti'), ('penalty_applied', "Jarima qo'llanildi"), ('extension_approved', 'Uzaytirish tasdiqlandi')], max_length=30, verbose_name='Turi'),
        ),
    ]
